// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// distance_matrix
Eigen::MatrixXd distance_matrix(Eigen::MatrixXd R, List clusters);
RcppExport SEXP _HRClusterpath_distance_matrix(SEXP RSEXP, SEXP clustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type R(RSEXP);
    Rcpp::traits::input_parameter< List >::type clusters(clustersSEXP);
    rcpp_result_gen = Rcpp::wrap(distance_matrix(R, clusters));
    return rcpp_result_gen;
END_RCPP
}
// HRClusterpath_unique
List HRClusterpath_unique(Eigen::MatrixXd R_init, List clusters_init, const Eigen::MatrixXd Gamma, const Eigen::MatrixXd W, double lambda, double eps_f, double eps_conv, double tol_opt, int iter_max);
RcppExport SEXP _HRClusterpath_HRClusterpath_unique(SEXP R_initSEXP, SEXP clusters_initSEXP, SEXP GammaSEXP, SEXP WSEXP, SEXP lambdaSEXP, SEXP eps_fSEXP, SEXP eps_convSEXP, SEXP tol_optSEXP, SEXP iter_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type R_init(R_initSEXP);
    Rcpp::traits::input_parameter< List >::type clusters_init(clusters_initSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type eps_f(eps_fSEXP);
    Rcpp::traits::input_parameter< double >::type eps_conv(eps_convSEXP);
    Rcpp::traits::input_parameter< double >::type tol_opt(tol_optSEXP);
    Rcpp::traits::input_parameter< int >::type iter_max(iter_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(HRClusterpath_unique(R_init, clusters_init, Gamma, W, lambda, eps_f, eps_conv, tol_opt, iter_max));
    return rcpp_result_gen;
END_RCPP
}
// Likelihood_raw
double Likelihood_raw(Eigen::MatrixXd R, List clusters, const Eigen::MatrixXd Gamma, const Eigen::MatrixXd P);
RcppExport SEXP _HRClusterpath_Likelihood_raw(SEXP RSEXP, SEXP clustersSEXP, SEXP GammaSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type R(RSEXP);
    Rcpp::traits::input_parameter< List >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(Likelihood_raw(R, clusters, Gamma, P));
    return rcpp_result_gen;
END_RCPP
}
// Likelihood_penalised
double Likelihood_penalised(Eigen::MatrixXd R, List clusters, const Eigen::MatrixXd Gamma, const Eigen::MatrixXd P, const Eigen::MatrixXd W, double lambda);
RcppExport SEXP _HRClusterpath_Likelihood_penalised(SEXP RSEXP, SEXP clustersSEXP, SEXP GammaSEXP, SEXP PSEXP, SEXP WSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type R(RSEXP);
    Rcpp::traits::input_parameter< List >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(Likelihood_penalised(R, clusters, Gamma, P, W, lambda));
    return rcpp_result_gen;
END_RCPP
}
// build_theta_cpp
Eigen::MatrixXd build_theta_cpp(Eigen::MatrixXd R, List clusters);
RcppExport SEXP _HRClusterpath_build_theta_cpp(SEXP RSEXP, SEXP clustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type R(RSEXP);
    Rcpp::traits::input_parameter< List >::type clusters(clustersSEXP);
    rcpp_result_gen = Rcpp::wrap(build_theta_cpp(R, clusters));
    return rcpp_result_gen;
END_RCPP
}
// non_singular_P
Eigen::MatrixXd non_singular_P(int d);
RcppExport SEXP _HRClusterpath_non_singular_P(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(non_singular_P(d));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HRClusterpath_distance_matrix", (DL_FUNC) &_HRClusterpath_distance_matrix, 2},
    {"_HRClusterpath_HRClusterpath_unique", (DL_FUNC) &_HRClusterpath_HRClusterpath_unique, 9},
    {"_HRClusterpath_Likelihood_raw", (DL_FUNC) &_HRClusterpath_Likelihood_raw, 4},
    {"_HRClusterpath_Likelihood_penalised", (DL_FUNC) &_HRClusterpath_Likelihood_penalised, 6},
    {"_HRClusterpath_build_theta_cpp", (DL_FUNC) &_HRClusterpath_build_theta_cpp, 2},
    {"_HRClusterpath_non_singular_P", (DL_FUNC) &_HRClusterpath_non_singular_P, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_HRClusterpath(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
