# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distance_matrix <- function(R, clusters) {
    .Call(`_HRClusterpath_distance_matrix`, R, clusters)
}

.HRClusterpath <- function(R_init, clusters_init, Gamma, W, lambda, eps_f, eps_conv, tol_opt, iter_max) {
    .Call(`_HRClusterpath_HRClusterpath_unique`, R_init, clusters_init, Gamma, W, lambda, eps_f, eps_conv, tol_opt, iter_max)
}

.Likelihood_HR <- function(R, clusters, Gamma, P) {
    .Call(`_HRClusterpath_Likelihood_raw`, R, clusters, Gamma, P)
}

.Penalty <- function(R, clusters, W) {
    .Call(`_HRClusterpath_Penalty`, R, clusters, W)
}

.Likelihood_penalised <- function(R, clusters, Gamma, P, W, lambda) {
    .Call(`_HRClusterpath_Likelihood_penalised`, R, clusters, Gamma, P, W, lambda)
}

.create_U <- function(clusters) {
    .Call(`_HRClusterpath_create_U`, clusters)
}

.build_theta <- function(R, clusters) {
    .Call(`_HRClusterpath_build_theta_cpp`, R, clusters)
}

.non_singular_P <- function(d) {
    .Call(`_HRClusterpath_non_singular_P`, d)
}

