# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_matrices_inplace <- function(out, A) {
    invisible(.Call(`_HRClusterpath_add_matrices_inplace`, out, A))
}

crout_decomposition_rcpp <- function(A, tol = 1e-8) {
    .Call(`_HRClusterpath_crout_decomposition_rcpp`, A, tol)
}

distance_matrix <- function(R, clusters) {
    .Call(`_HRClusterpath_distance_matrix`, R, clusters)
}

step <- function() {
    invisible(.Call(`_HRClusterpath_step`))
}

s_optimal <- function(s, f) {
    .Call(`_HRClusterpath_s_optimal`, s, f)
}

penalty_grad_rcpp <- function(K, f) {
    .Call(`_HRClusterpath_penalty_grad_rcpp`, K, f)
}

psolve_rcpp <- function(L_) {
    .Call(`_HRClusterpath_psolve_rcpp`, L_)
}

