# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.distance_matrix <- function(R_matrix, clusters) {
    .Call(`_HRClusterpath_distance_matrix`, R_matrix, clusters)
}

.HRClusterpath <- function(R_init, clusters_init, Gamma, W_cluster, W_lasso, lambda, mu, eps_lasso, eps_f, EPS_CONV, TOL_OPT, MAX_ITER) {
    .Call(`_HRClusterpath_HRClusterpath_unique`, R_init, clusters_init, Gamma, W_cluster, W_lasso, lambda, mu, eps_lasso, eps_f, EPS_CONV, TOL_OPT, MAX_ITER)
}

.Likelihood_HR <- function(R_matrix, clusters, Gamma, P) {
    .Call(`_HRClusterpath_Likelihood_raw`, R_matrix, clusters, Gamma, P)
}

.Penalty <- function(R_matrix, clusters, W_cluster) {
    .Call(`_HRClusterpath_Penalty`, R_matrix, clusters, W_cluster)
}

.Likelihood_penalised <- function(R_init, clusters, Gamma, P, W_cluster, W_lasso, lambda, mu, eps_lasso) {
    .Call(`_HRClusterpath_Likelihood_penalised`, R_init, clusters, Gamma, P, W_cluster, W_lasso, lambda, mu, eps_lasso)
}

.create_U <- function(D_VARIABLE, clusters) {
    .Call(`_HRClusterpath_create_U`, D_VARIABLE, clusters)
}

.build_theta <- function(D_VARIABLE, R_matrix, clusters) {
    .Call(`_HRClusterpath_build_theta_cpp`, D_VARIABLE, R_matrix, clusters)
}

.non_singular_P <- function(dim) {
    .Call(`_HRClusterpath_non_singular_P`, dim)
}

